employees/urls.py
from django.urls import path

from . import views


app_name = 'employees'  # namespace of the app for scalability
urlpatterns = [
    path('', views.index, name = 'index'),  # the homepage of employees
    path('dept/<int:dept_id>/', views.details, name = 'details'),
]

focus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('employees.urls')),
    path('admin/', admin.site.urls),
]

employees/models.py
from django.db import models

# Create your models here.


class Color(models.Model):
    # id primary key is created automaticly
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    #change the default table name to the one in the word document
    class Meta:
        db_table = "Color"
    

class Department(models.Model):
    # id primary key is created automaticly
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    #change the default table name to the one in the word document
    class Meta:
        db_table = "Department"
    

class Employees(models.Model):
    #TODO: check why the sql command doesnt write it as foreignkey
    # id primary key is created automaticly
    name           = models.CharField(max_length=200)
    age            = models.IntegerField()
    is_senior      = models.BooleanField(default=True)   # as requested in the wor document
    favorite_color = models.ForeignKey(Color, on_delete=models.CASCADE, default=2, db_column='favorite_color') # TODO: change cascade to a better function so it wont delete the object
    department     = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='department'
                                        , default=None) # TODO: change cascade to a better function so it wont delete the object
    
    def __str__(self):
        return self.name
    

    # def __repr__(self):
    #     return self.name

    #change the default table name to the one in the word document
    class Meta:
        db_table = "Employees"

    

employees/forms.py
from django.forms import ModelForm
from django import forms

from .models import Employees, Color, Department

#we want to change only the senior and color
class EmployeeForm(ModelForm):

    class Meta:
        model = Employees
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}),
            'age' : forms.NumberInput(attrs={'readonly': True, 'class': 'form-control'}),
            'is_senior' : forms.CheckboxInput(attrs={'class':'ml-4'}),
            'favorite_color': forms.Select(attrs={'class': ''}),
        }
    
    # class Meta:
    #     model = Employees
    #     fields = '__all__'

    #     widgets = {
    #         'name': forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}),
    #         'age' : forms.NumberInput(attrs={'readonly': True, 'class': 'form-control'}),
    #         'is_senior' : forms.CheckboxInput(attrs={'class':'ml-4'}),
    #         'favorite_color': forms.Select(attrs={'class': ''}),
    #         'department': forms.HiddenInput(),
    #         'id': forms.HiddenInput(),
    #     }
        # alot of redundant widgets because had problems with hidden inputs

employees/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect, reverse
from django.http import HttpResponse
from django.forms import modelformset_factory
from django.contrib import messages

from .models import Department, Employees, Color
from .forms import EmployeeForm

# Create your views here.

# homepage where you choose a department 
def index(request):
    lst_of_deps = Department.objects.order_by('id')   #get list of ids
    context = {'lst_of_deps' : lst_of_deps} 
    return render(request, 'employees/index.html', context)


def test(request):
    return HttpResponse("This is a Test!")


# show emps in the department once you chose a department 
def details(request, dept_id):
    dept = get_object_or_404(Department, id=dept_id)   #get the departnet object

    #create modelformset to change multiple fields from multiple forms together    
    emps_formset = modelformset_factory(Employees, form=EmployeeForm, fields=('name', 'age', 'is_senior', 'favorite_color'), extra=0)
    #formset =  emps_formset(queryset=Employees.objects.filter(department=dept_id))

    if request.method == 'POST':
        formset =  emps_formset(request.POST)
        instances = formset.save()
        messages.info(request, 'Your Changes Have Been Commited')

    # prep the template
    
    formset =  emps_formset(queryset=Employees.objects.filter(department=dept_id))
    context = {
        'dept'      : dept,
        'formset'    : formset,
    }
    return render(request, 'employees/details.html', context)


# def details(request, dept_id):
#     dept = get_object_or_404(Department, id=dept_id)   #test
#     lst_of_emps = get_list_or_404(Employees, department=dept_id)

#     #create modelformset to change multiple filed  from multiple forms together
#     emps_formset = modelformset_factory(Employees, fields=('is_senior', 'favorite_color'))

#     context = {
#         'depts': dept,
#         'lst_of_emps': lst_of_emps,
#     }

#     return render(request, 'employees/details.html', context)

employees/templates/employees/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}{% endblock %}
    <title>{% block title %} Focus {% endblock %}</title>

    
 
</head>
<body>
    <nav class="navbar navbar-expanded-large navbar-dark bg-dark">
        <ul class="nav-nav">
            <li class="nav-item">
                <a class="nav-link text-light" href="/"><h4 >Focus</h4></a>
            </li>
        </ul>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </div>
</body>
</html>

employees/templates/employees/details.html
{% extends 'employees/base.html' %}

{% block title %}{{ dept.name }}{% endblock %}
{% block style %}
{% endblock %}


{% block body %}

<!-- display a message if saved to db -->
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Heads Up!</strong> {{ message }}.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<h1>{{ dept.name }}</h1>
<hr/>
<form method="post">
    {% csrf_token %}   
    <div class="d-flex flex-wrap ">
        {{ formset.management_form }}
        {% for form in formset %}
        <div class="w-25  m-2" >
            <div class="bg-primary rounded border  ">
                {{ form }}
            </div>
            
        </div>
        {% endfor %}
    </div>
    
    <div class="col-md-12 text-center ">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

employees/templates/employees/index.html
{% extends 'employees/base.html' %}

{% block title %}Focus{% endblock %}

{% block body %}
    <h1 class="text-center">Choose a department</h1>
    <hr class="border border-info border-3 opacity-75"/>
    {% if lst_of_deps %}
    <div class="row">
        {% for dept in lst_of_deps %}
        <div class="col-sm-6">
          <div class="card m-1">
            <div class="card-header text-center">
                <h5 class="card-title">{{ dept.name }}</h5>
            </div>
            <div class="card-body text-center">
              <p class="card-text">see the list of {{ dept.name }} employees</p>
              <a href="{% url 'employees:details' dept.id %}" class="btn btn-primary">Go There Now!!</a>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <p>Theres no departments!</p>
    {% endif %}
{% endblock %}